#pragma once

//#include <bit>
//#include <span>
#include <mutex>
#include <array>
//#include <atomic>
#include <vector>
#include <string>
//#include <cctype>
//#include <memory>
//#include <format>
//#include <locale>
//#include <future>
//#include <fstream>
#include <sstream>
#include <variant>
#include <utility>
//#include <codecvt>
//#include <cstdint>
//#include <cassert>
//#include <iostream>
//#include <algorithm>
#include <stdexcept>
//#include <filesystem>
#include <functional>
//#include <string_view>
//#include <type_traits>
//#include <shared_mutex>
//#include <unordered_map>
#include <source_location>

#include "Headers/PlatformsDefines.h"
#include "Headers/HeadersMSWin.h"
#include "Headers/HeaderVulkan.h"
#include "Headers/HeaderMetal.h"
#include "Headers/HeaderDX.h"
#include "Headers/MacroDefinition.h"
#include "Headers/HeaderTypes.h"
#include "Headers/HeaderConstants.h"

#include "Headers/HeaderTemplates.h"
