#pragma once

#include <bit>
#include <span>
#include <mutex>
#include <array>
#include <atomic>
#include <vector>
#include <string>
#include <cctype>
#include <memory>
#include <format>
#include <locale>
#include <future>
#include <fstream>
#include <sstream>
#include <variant>
#include <utility>
#include <codecvt>
#include <cstdint>
#include <cassert>
#include <iostream>
#include <algorithm>
#include <stdexcept>
#include <filesystem>
#include <functional>
#include <string_view>
#include <type_traits>
#include <shared_mutex>
#include <unordered_map>
#include <source_location>

#include "PlatformsDefines.h"
#include "HeadersMSWin.h"
#include "HeaderVulkan.h"
#include "HeaderMetal.h"
#include "headerDX.h"
#include "MacroDefinition.h"
#include "HeaderTypes.h"
#include "HeaderTemplates.h"