<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Properties\AppIcon.ico</ApplicationIcon>

    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU;x64</Platforms>

    <OutputPath>..\..\..\..\dist\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\assets_builder_lib\assets_builder_lib.csproj" />
    <Resource Include="Properties\AppIcon.ico" />
  </ItemGroup>

</Project>
