#pragma once

#include "core/CoreIncludes.h"

#include "core/utils/Types.h"
#include "core/utils/Export.h"
#include "core/utils/Constants.h"
#include "core/utils/Defines.h"
#include "core/utils/Ensure.h"
#include "core/utils/Guid.h"
#include "core/utils/Macroses.h"
#include "core/utils/MemoryUtils.h"
#include "core/utils/Version.h"
#include "core/utils/Converters.h"

#include "core/enums/ePackage.h"
#include "core/enums/eTargetPlatform.h"
#include "core/enums/eGAPIType.h"
#include "core/enums/eWindowState.h"
#include "core/enums/eLogMessageType.h"
#include "core/enums/eEnumToString.h"
#include "core/enums/eWinResize.h"
#include "core/enums/platforms/ConverterMSWinTypes.h"
#include "core/enums/platforms/ConverterAndroidTypes.h"
#include "core/enums/platforms/ConverteriOSTypes.h"
#include "core/enums/platforms/ConverterLinuxTypes.h"
#include "core/enums/platforms/ConverterMacOSTypes.h"

#include "core/serialize/Serializer.h"

#include "core/templates/DoubleBufferedVector.h"

#include "core/time/Time.h"
#include "core/events/Event.h"
#include "core/events/EventBus.h"

#include "core/userscripts/ScriptStorage.h"
#include "core/userscripts/ScriptFactory.h"
#include "core/userscripts/ScriptRegistry.h"
#include "core/userscripts/base_script/BaseScript.h"
#include "core/userscripts/base_script/Script.h"
#include "core/userscripts/base_script/GameScript.h"
#include "core/userscripts/base_script/SceneScript.h"
#include "core/userscripts/base_script/ViewScript.h"

#include "core/io/FileHeader.h"
#include "core/io/Path.h"
#include "core/io/package/PackageHeader.h"
#include "core/io/package/PackageEntry.h"
#include "core/io/package/PrimaryViewData.h"
#include "core/io/package/PrimaryViewUserData.h"
#include "core/io/package/ViewUserData.h"
#include "core/io/package/ViewData.h"
#include "core/io/package/ProjectManifestData.h"
#include "core/io/package/SceneData.h"
#include "core/io/package/PrefabData.h"
#include "core/io/package/platforms/project/ProjectPlatformConfig.h"
#include "core/io/package/platforms/project/ProjectPlatformDataAndroid.h"
#include "core/io/package/platforms/project/ProjectPlatformDataLinux.h"
#include "core/io/package/platforms/project/ProjectPlatformDataMSWin.h"
#include "core/io/package/platforms/project/ProjectPlatformDataMacOS.h"
#include "core/io/package/platforms/project/ProjectPlatformDataiOS.h"
#include "core/io/package/platforms/start_view/ViewPlatformConfig.h"
#include "core/io/package/platforms/start_view/ViewDataAndroid.h"
#include "core/io/package/platforms/start_view/ViewDataLinux.h"
#include "core/io/package/platforms/start_view/ViewDataMSWin.h"
#include "core/io/package/platforms/start_view/ViewDataMacOS.h"
#include "core/io/package/platforms/start_view/ViewDataiOS.h"

#include "core/hardware/CpuInfo.h"
#include "core/hardware/GpuInfo.h"
#include "core/hardware/RamInfo.h"
#include "core/hardware/MotherboardInfo.h"
#include "core/hardware/MonitorInfo.h"
#include "core/hardware/StorageInfo.h"
#include "core/hardware/NetworkAdapterInfo.h"
#include "core/hardware/HardwareState.h"

using namespace zzz::math;

