#pragma once

#include "core/CoreIncludes.h"

#include "core/utils/Types.h"
#include "core/utils/Export.h"
#include "core/utils/Constants.h"
#include "core/utils/Defines.h"
#include "core/utils/Ensure.h"
#include "core/utils/Guid.h"
#include "core/utils/Macroses.h"
#include "core/utils/MemoryUtils.h"
#include "core/utils/ScreenResolution.h"
#include "core/utils/ThrowWrappers.h"
#include "core/utils/Version.h"
#include "core/utils/Converters.h"

#include "core/enums/ePackage.h"
#include "core/enums/eTargetPlatform.h"
#include "core/enums/eGAPIType.h"
#include "core/enums/eEnumToString.h"
#include "core/enums/eLogMessageType.h"
#include "core/enums/eWinResize.h"
#include "core/enums/platforms/ConverterMSWinTypes.h"
#include "core/enums/platforms/ConverterAndroidTypes.h"
#include "core/enums/platforms/ConverteriOSTypes.h"
#include "core/enums/platforms/ConverterLinuxTypes.h"
#include "core/enums/platforms/ConverterMacOSTypes.h"

#include "core/serialize/Serializer.h"

#include "core/templates/DoubleBufferedVector.h"
#include "core/templates/Size2D.h"

#include "core/time/Time.h"
#include "core/events/Event.h"
#include "core/events/EventBus.h"

#include "core/userscripts/ScriptRegistry.h"
#include "core/userscripts/base_script/BaseScript.h"
#include "core/userscripts/base_script/Script.h"
#include "core/userscripts/base_script/GameScript.h"
#include "core/userscripts/base_script/SceneScript.h"
#include "core/userscripts/base_script/ViewScript.h"

#include "core/io/FileHeader.h"
#include "core/io/Path.h"
#include "core/io/config/PlatformConfig.h"
#include "core/io/config/platforms/ConfigAndroid.h"
#include "core/io/config/platforms/ConfigEditor.h"
#include "core/io/config/platforms/ConfigLinux.h"
#include "core/io/config/platforms/ConfigMSWin.h"
#include "core/io/config/platforms/ConfigMacOS.h"
#include "core/io/config/platforms/ConfigiOS.h"
#include "core/io/package/PackageHeader.h"
#include "core/io/package/PackageEntry.h"
#include "core/io/package/AppViewData.h"
#include "core/io/package/AppViewUserData.h"
#include "core/io/package/ViewData.h"
#include "core/io/package/ProjectManifestData.h"
#include "core/io/package/SceneData.h"
#include "core/io/package/PrefabData.h"
#include "core/io/package/platforms/AppViewPlatformConfig.h"
#include "core/io/package/platforms/AppViewDataAndroid.h"
#include "core/io/package/platforms/AppViewDataLinux.h"
#include "core/io/package/platforms/AppViewDataMSWin.h"
#include "core/io/package/platforms/AppViewDataMacOS.h"
#include "core/io/package/platforms/AppViewDataiOS.h"
