#pragma once

#include "math/MathIncludes.h"
#include "math/utils/MathConstants.h"
#include "math/utils/MathUtils.h"
#include "math/utils/color/Color.h"
#include "math/geometry/Point2D.h"
#include "math/geometry/Size2D.h"
#include "math/geometry/Rect2D.h"
#include "math/vector/Vec2.h"
#include "math/vector/Vec3.h"
#include "math/vector/Vec4.h"
#include "math/matrix/Mat3.h"
#include "math/matrix/Mat4.h"
#include "math/quat/Quat.h"
