# Auto-generated file.
# Configuration: WIN_VULKAN

set(Z_TESTS_ENABLE_COMMON OFF)
set(Z_TESTS_BENCH_ENABLE_COMMON OFF)
set(Z_ADD_PROJECT_TESTS_IN_BUILD OFF)
set(Z_ADD_PROJECT_BENCHMARKS_IN_BUILD OFF)

add_compile_definitions(
    Z_ADD_LOGGER=1
    Z_IDE_OUT_LOGS=1
    Z_FORCE_VULKAN=1
)
