# Auto-generated file.
# Configuration: WIN_VULKAN_LOGS

set(Z_FORCE_VULKAN ON)
set(Z_TESTS_ENABLE_COMMON ON)
set(Z_TESTS_BENCH_ENABLE_COMMON ON)
set(Z_ADD_PROJECT_TESTS_IN_BUILD ON)
set(Z_ADD_PROJECT_BENCHMARKS_IN_BUILD ON)

add_compile_definitions(
    Z_ADD_LOGGER=1
    Z_IDE_OUT_LOGS=1
)
