# Auto-generated file.
# Configuration: WIN_DX_LOGS

set(Z_ADD_PROJECT_BENCHMARKS_IN_BUILD ON)
set(Z_ADD_PROJECT_TESTS_IN_BUILD ON)
set(Z_FORCE_VULKAN OFF)
set(Z_TESTS_BENCH_ENABLE_COMMON ON)
set(Z_TESTS_ENABLE_COMMON ON)

add_compile_definitions(
    Z_ADD_LOGGER=1
    Z_GAPI_VERBOSE_DEBUG_LAYER=0
    Z_IDE_OUT_LOGS=1
)
